config/routes.rb
GroceryList::Application.routes.draw do
  resources :groceries

  get "home/index"

   root 'home#index'

end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
  before_action :set_grocery, only: [:show, :edit, :update, :destroy]

  # GET /groceries
  # GET /groceries.json
  def index
    @groceries = Grocery.all
  end

  # GET /groceries/1
  # GET /groceries/1.json
  def show
  end

  # GET /groceries/new
  def new
    @grocery = Grocery.new
  end

  # GET /groceries/1/edit
  def edit
  end

  # POST /groceries
  # POST /groceries.json
  def create
    @grocery = Grocery.new(grocery_params)

    respond_to do |format|
      if @grocery.save
        format.html { redirect_to @grocery, notice: 'Grocery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @grocery }
      else
        format.html { render action: 'new' }
        format.json { render json: @grocery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groceries/1
  # PATCH/PUT /groceries/1.json
  def update
    respond_to do |format|
      if @grocery.update(grocery_params)
        format.html { redirect_to @grocery, notice: 'Grocery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @grocery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groceries/1
  # DELETE /groceries/1.json
  def destroy
    @grocery.destroy
    respond_to do |format|
      format.html { redirect_to groceries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grocery
      @grocery = Grocery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grocery_params
      params.require(:grocery).permit(:item, :price, :healthy, :bought)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/groceries/_form.html.erb
<%= form_for(@grocery) do |f| %>
  <% if @grocery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grocery.errors.count, "error") %> prohibited this grocery from being saved:</h2>

      <ul>
      <% @grocery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :healthy %><br>
    <%= f.check_box :healthy %>
  </div>
  <div class="field">
    <%= f.label :bought %><br>
    <%= f.check_box :bought %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groceries/edit.html.erb
<h1>Editing grocery</h1>

<%= render 'form' %>

<%= link_to 'Show', @grocery %> |
<%= link_to 'Back', groceries_path %>

app/views/groceries/index.html.erb
<h1>Listing groceries</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th>Healthy</th>
      <th>Bought</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groceries.each do |grocery| %>
      <tr>
        <td><%= grocery.item %></td>
        <td><%= grocery.price %></td>
        <td><%= grocery.healthy %></td>
        <td><%= grocery.bought %></td>
        <td><%= link_to 'Show', grocery %></td>
        <td><%= link_to 'Edit', edit_grocery_path(grocery) %></td>
        <td><%= link_to 'Destroy', grocery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grocery', new_grocery_path %>

app/views/groceries/new.html.erb
<h1>New grocery</h1>

<%= render 'form' %>

<%= link_to 'Back', groceries_path %>

app/views/groceries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @grocery.item %>
</p>

<p>
  <strong>Price:</strong>
  <%= @grocery.price %>
</p>

<p>
  <strong>Healthy:</strong>
  <%= @grocery.healthy %>
</p>

<p>
  <strong>Bought:</strong>
  <%= @grocery.bought %>
</p>

<%= link_to 'Edit', edit_grocery_path(@grocery) %> |
<%= link_to 'Back', groceries_path %>

app/views/home/index.html.erb
<header></header>
<section class="main" ng-controller="GroceryCtrl">
	<div id="wrapper">
		<div class="header">
			<h1>Your Grocery List!</h1>
			<span id="form_intro">Fill out the form below to track your groceries and denote which items are healthy. The more green the better!</<span>
		</div>
		<div class="food">
			<ul ng-repeat="food in foods">
				<li>
					<a href="#" ng-click="addFood($event, food)">{{food.food}}</a>
				</li>
			</ul>
		</div>
		<div>
			

		</div>
		<div class="form_container">
			<form name="grocery_list" ng-submit="addItem($event)">
				<span id="form_text" style="margin-top:20px;">You want to buy...?</span><br>
				<input class="input item" type="text" ng-model="item" placeholder="ie: Apples, Oranges, etc" required/>
				
				<br/>
				<div >
					<div class="costs">
						<span id="form_text">Cost?</span>
						<br/>
						<input class="input_cost" placeholder="$.$$" type="text" required ng-model="cost"/>
					</div>
					<div  class="all-costs" 
						ng-show="showTotal"
						ng-animate="{show: 'show-costs', hide: 'hide-costs}'">
						<div class="listed-costs">
							<span id="form_text">Total Cost: </span>
							<span id="total_bill">{{ totalCost | currency }}</span>
						</div>
						<div class="listed-costs">
							<span  id="form_text">Healthy Cost: </span>
							<span id="healthy-costs">{{ healthyCost | currency }}</span>
						</div>
						<div class="listed-costs">
							<span  id="form_text">Unhealthy Cost: </span>
							<span id="bad-costs">{{ badCost | currency }}</span>
						</div>
						
					</div>
					<div class="lower-div">
						<div>
							<span id="form_text">Is this healthy?</span><input class="checker" type="checkbox" ng-model="healthy"/>
						</div>
					</div>
				</div>

				<br/>

				<button ng-click="addItem($event)">Add It!</button>
			</form>
		</div>
		<div class="list">
			<ul ng-repeat="i in groceries">
				<li ng-class="{
					healthy: i.healthy === true,
					bought: i.bought === true,
					bad: i.healthy === false}">
					<input type="checkbox" ng-checked="{{i.bought}}" ng-click="toggleBought(i)" ng-model="i.bought">
					{{i.item}}
					&nbsp;
					<span class="price">{{i.price | currency}}</span>
					<span class="right" ng-click="deleteItem($index, i)">x</span>
				</li>
			</ul>
		</div>
	</div>
</section>
	
<!-- here are the steps to setting up an ANgularJS app in rails
1. add the 'gem 'angularjs-rails' gem
2. run BUNDLE INSTALL	
3. go into application.js and require angular  and angular-resource 
	1. //=require angular
	2. //=require angular-resource
4. add resources: items to the routes.rb file (here, 'items' is what I named my array that's used)
5. add in the ng-app directive and name
6. create the rails scaffold >> rails g scaffold Item title:string (can add more database columns here)
7. run rake routes & db migrate >>
>>rake routes
>>rake db:migrate
8. REmember: I may have to shut down and restart the server. So, reboot the server.
9. have to add in this token and statement to the js file:

app.config(function ($httpProvider) {
  // CSRF
  $httpProvider.defaults.headers.common['X-CSRF-Token'] = $('meta[name=csrf-token]').attr('content');
});
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="groceryApp">
<head>
  <title>GroceryList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>